@startuml

digraph foo {
  node [style=rounded]
  I[fillcolor=yellow]
  F[fillcolor=yellow]
  
  I -> p1 
  
  p1 -> p2 
  p2 -> p4 
  p2 -> p6
  p2 -> p3 
  p2 -> p5 

  p4 -> p7 
  p6 -> p7 
  p3 -> p9 
  p5 -> p9 
  p4 -> p8 
  p6 -> p8 
  
  p7 -> p10 
  p8 -> p10 
  p9 -> p10 

  p10 -> p11 
  p11 -> p11 
  p11 -> p12 

  p12 -> F 
}